# Setup
title:               Amey Palyekar
tagline:             
description:         'Data Analysis and Machine Learning in R, Python'
url:                 http://apalyekar.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Amey Palyekar
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
